
package function;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "impala", targetNamespace = "impalans", wsdlLocation = "http://impala.molgen.mpg.de/download/IMPALA.wsdl")
public class Impala
        extends Service {

    private final static URL IMPALA_WSDL_LOCATION;
    private final static WebServiceException IMPALA_EXCEPTION;
    private final static QName IMPALA_QNAME = new QName("impalans", "impala");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://impala.molgen.mpg.de/download/IMPALA.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMPALA_WSDL_LOCATION = url;
        IMPALA_EXCEPTION = e;
    }

    public Impala() {
        super(__getWsdlLocation(), IMPALA_QNAME);
    }

    public Impala(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPALA_QNAME, features);
    }

    public Impala(URL wsdlLocation) {
        super(wsdlLocation, IMPALA_QNAME);
    }

    public Impala(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPALA_QNAME, features);
    }

    public Impala(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Impala(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * ...
     *
     * @return returns ImpalaPortType
     */
    @WebEndpoint(name = "impala_port")
    public ImpalaPortType getImpalaPort() {
        return super.getPort(new QName("impalans", "impala_port"), ImpalaPortType.class);
    }

    /**
     * ...
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ImpalaPortType
     */
    @WebEndpoint(name = "impala_port")
    public ImpalaPortType getImpalaPort(WebServiceFeature... features) {
        return super.getPort(new QName("impalans", "impala_port"), ImpalaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPALA_EXCEPTION != null) {
            throw IMPALA_EXCEPTION;
        }
        return IMPALA_WSDL_LOCATION;
    }

}
