
package function;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "impala_portType", targetNamespace = "impalans")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ImpalaPortType {


    /**
     * Performs joint over-representation analysis on pathways with a list of significant genes, a list of significant metabolites, and optional background lists of genes / metabolites.
     *
     * @param metaboliteAccType
     * @param pMetabolites
     * @param qJoint
     * @param geneAccFg
     * @param overlappingGenesNum
     * @param qGenes
     * @param allMetabolitesNum
     * @param pathwaySource
     * @param overlappingMetabolites
     * @param metaboliteAccFg
     * @param pathwayName
     * @param allGenesNum
     * @param metaboliteAccBg
     * @param overlappingGenes
     * @param qMetabolites
     * @param overlappingMetabolitesNum
     * @param pGenes
     * @param geneAccBg
     * @param geneAccType
     * @param pJoint
     */
    @WebMethod(action = "impalans#pathwayORAjoint")
    @RequestWrapper(localName = "pathwayORAjoint", targetNamespace = "impalans", className = "function.PathwayORAjoint")
    @ResponseWrapper(localName = "pathwayORAjointResponse", targetNamespace = "impalans", className = "function.PathwayORAjointResponse")
    public void pathwayORAjoint(
            @WebParam(name = "geneAccType", targetNamespace = "impalans")
                    String geneAccType,
            @WebParam(name = "geneAccFg", targetNamespace = "impalans")
                    List<String> geneAccFg,
            @WebParam(name = "geneAccBg", targetNamespace = "impalans")
                    List<String> geneAccBg,
            @WebParam(name = "metaboliteAccType", targetNamespace = "impalans")
                    String metaboliteAccType,
            @WebParam(name = "metaboliteAccFg", targetNamespace = "impalans")
                    List<String> metaboliteAccFg,
            @WebParam(name = "metaboliteAccBg", targetNamespace = "impalans")
                    List<String> metaboliteAccBg,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "overlappingGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> overlappingGenesNum,
            @WebParam(name = "overlappingGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> overlappingGenes,
            @WebParam(name = "allGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allGenesNum,
            @WebParam(name = "pGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pGenes,
            @WebParam(name = "qGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qGenes,
            @WebParam(name = "overlappingMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> overlappingMetabolitesNum,
            @WebParam(name = "overlappingMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> overlappingMetabolites,
            @WebParam(name = "allMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allMetabolitesNum,
            @WebParam(name = "pMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pMetabolites,
            @WebParam(name = "qMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qMetabolites,
            @WebParam(name = "pJoint", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pJoint,
            @WebParam(name = "qJoint", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qJoint);

    /**
     * Performs over-representation analysis on pathways with a list of significant genes and an optional background list of genes.
     *
     * @param geneAccFg
     * @param overlappingGenesNum
     * @param qGenes
     * @param pathwaySource
     * @param pGenes
     * @param geneAccBg
     * @param geneAccType
     * @param pathwayName
     * @param allGenesNum
     * @param overlappingGenes
     */
    @WebMethod(action = "impalans#pathwayORAgenes")
    @RequestWrapper(localName = "pathwayORAgenes", targetNamespace = "impalans", className = "function.PathwayORAgenes")
    @ResponseWrapper(localName = "pathwayORAgenesResponse", targetNamespace = "impalans", className = "function.PathwayORAgenesResponse")
    public void pathwayORAgenes(
            @WebParam(name = "geneAccType", targetNamespace = "impalans")
                    String geneAccType,
            @WebParam(name = "geneAccFg", targetNamespace = "impalans")
                    List<String> geneAccFg,
            @WebParam(name = "geneAccBg", targetNamespace = "impalans")
                    List<String> geneAccBg,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "overlappingGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> overlappingGenesNum,
            @WebParam(name = "overlappingGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> overlappingGenes,
            @WebParam(name = "allGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allGenesNum,
            @WebParam(name = "pGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pGenes,
            @WebParam(name = "qGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qGenes);

    /**
     * Performs over-representation analysis on pathways with a list of significant metabolites and an optional background list of metabolites.
     *
     * @param metaboliteAccType
     * @param pMetabolites
     * @param qMetabolites
     * @param allMetabolitesNum
     * @param pathwaySource
     * @param overlappingMetabolitesNum
     * @param overlappingMetabolites
     * @param metaboliteAccFg
     * @param pathwayName
     * @param metaboliteAccBg
     */
    @WebMethod(action = "impalans#pathwayORAmetabolites")
    @RequestWrapper(localName = "pathwayORAmetabolites", targetNamespace = "impalans", className = "function.PathwayORAmetabolites")
    @ResponseWrapper(localName = "pathwayORAmetabolitesResponse", targetNamespace = "impalans", className = "function.PathwayORAmetabolitesResponse")
    public void pathwayORAmetabolites(
            @WebParam(name = "metaboliteAccType", targetNamespace = "impalans")
                    String metaboliteAccType,
            @WebParam(name = "metaboliteAccFg", targetNamespace = "impalans")
                    List<String> metaboliteAccFg,
            @WebParam(name = "metaboliteAccBg", targetNamespace = "impalans")
                    List<String> metaboliteAccBg,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "overlappingMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> overlappingMetabolitesNum,
            @WebParam(name = "overlappingMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> overlappingMetabolites,
            @WebParam(name = "allMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allMetabolitesNum,
            @WebParam(name = "pMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pMetabolites,
            @WebParam(name = "qMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qMetabolites);

    /**
     * Performs joint Wilcoxon enrichment analysis on pathways with a list of all measured genes and a list of all measured metabolites, with either one or two numerical values for each gene and each metabolite.
     *
     * @param metaboliteAccType
     * @param pMetabolites
     * @param qJoint
     * @param qGenes
     * @param allMetabolitesNum
     * @param pathwaySource
     * @param measuredMetabolites
     * @param metaboliteAccs
     * @param pathwayName
     * @param allGenesNum
     * @param measuredMetabolitesNum
     * @param qMetabolites
     * @param geneAccs
     * @param pGenes
     * @param measuredGenes
     * @param geneAccType
     * @param measuredGenesNum
     * @param pJoint
     */
    @WebMethod(action = "impalans#pathwayWEAjoint")
    @RequestWrapper(localName = "pathwayWEAjoint", targetNamespace = "impalans", className = "function.PathwayWEAjoint")
    @ResponseWrapper(localName = "pathwayWEAjointResponse", targetNamespace = "impalans", className = "function.PathwayWEAjointResponse")
    public void pathwayWEAjoint(
            @WebParam(name = "geneAccType", targetNamespace = "impalans")
                    String geneAccType,
            @WebParam(name = "geneAccs", targetNamespace = "impalans")
                    List<String> geneAccs,
            @WebParam(name = "metaboliteAccType", targetNamespace = "impalans")
                    String metaboliteAccType,
            @WebParam(name = "metaboliteAccs", targetNamespace = "impalans")
                    List<String> metaboliteAccs,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "measuredGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> measuredGenesNum,
            @WebParam(name = "measuredGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> measuredGenes,
            @WebParam(name = "allGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allGenesNum,
            @WebParam(name = "pGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pGenes,
            @WebParam(name = "qGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qGenes,
            @WebParam(name = "measuredMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> measuredMetabolitesNum,
            @WebParam(name = "measuredMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> measuredMetabolites,
            @WebParam(name = "allMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allMetabolitesNum,
            @WebParam(name = "pMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pMetabolites,
            @WebParam(name = "qMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qMetabolites,
            @WebParam(name = "pJoint", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pJoint,
            @WebParam(name = "qJoint", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qJoint);

    /**
     * Performs Wilcoxon enrichment analysis on pathways with a list of all measured genes with either one or two numerical values per gene.
     *
     * @param geneAccs
     * @param qGenes
     * @param pathwaySource
     * @param pGenes
     * @param measuredGenes
     * @param geneAccType
     * @param pathwayName
     * @param allGenesNum
     * @param measuredGenesNum
     */
    @WebMethod(action = "impalans#pathwayWEAgenes")
    @RequestWrapper(localName = "pathwayWEAgenes", targetNamespace = "impalans", className = "function.PathwayWEAgenes")
    @ResponseWrapper(localName = "pathwayWEAgenesResponse", targetNamespace = "impalans", className = "function.PathwayWEAgenesResponse")
    public void pathwayWEAgenes(
            @WebParam(name = "geneAccType", targetNamespace = "impalans")
                    String geneAccType,
            @WebParam(name = "geneAccs", targetNamespace = "impalans")
                    List<String> geneAccs,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "measuredGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> measuredGenesNum,
            @WebParam(name = "measuredGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> measuredGenes,
            @WebParam(name = "allGenesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allGenesNum,
            @WebParam(name = "pGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pGenes,
            @WebParam(name = "qGenes", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qGenes);

    /**
     * Performs Wilcoxon enrichment analysis on pathways with a list of all measured metabolites with either one or two numerical values per metabolite.
     *
     * @param metaboliteAccType
     * @param pMetabolites
     * @param qMetabolites
     * @param allMetabolitesNum
     * @param pathwaySource
     * @param measuredMetabolites
     * @param metaboliteAccs
     * @param pathwayName
     * @param measuredMetabolitesNum
     */
    @WebMethod(action = "impalans#pathwayWEAmetabolites")
    @RequestWrapper(localName = "pathwayWEAmetabolites", targetNamespace = "impalans", className = "function.PathwayWEAmetabolites")
    @ResponseWrapper(localName = "pathwayWEAmetabolitesResponse", targetNamespace = "impalans", className = "function.PathwayWEAmetabolitesResponse")
    public void pathwayWEAmetabolites(
            @WebParam(name = "metaboliteAccType", targetNamespace = "impalans")
                    String metaboliteAccType,
            @WebParam(name = "metaboliteAccs", targetNamespace = "impalans")
                    List<String> metaboliteAccs,
            @WebParam(name = "pathwayName", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwayName,
            @WebParam(name = "pathwaySource", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pathwaySource,
            @WebParam(name = "measuredMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<Integer>> measuredMetabolitesNum,
            @WebParam(name = "measuredMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> measuredMetabolites,
            @WebParam(name = "allMetabolitesNum", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> allMetabolitesNum,
            @WebParam(name = "pMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> pMetabolites,
            @WebParam(name = "qMetabolites", targetNamespace = "impalans", mode = WebParam.Mode.OUT)
                    Holder<List<String>> qMetabolites);

}
